# This file contains example settings which should mostly work for own deployment. Of course you need to enter your own domain and access data.


# #############################################################################
# general settings (no action necessary)
# #############################################################################

# valid values are "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
LOGLEVEL = "INFO"


# #############################################################################
# deployment settings which needs to be changed
# #############################################################################


remote = 'some_asteroid.uberspace.de'
user = 'some_user'

# #############################################################################
# deployment settings which should be OK for most use cases
# #############################################################################


app_name = "simplefeedback"
PROJECT_NAME = 'simplefeedback1'
url_path = "/%(app_name)s"
port = "8000"

ALLOWED_HOSTS = ["%(app_name)s.%(user)s.uber.space", "%(app_name)s.kddk.eu"]
ALLOWED_HOSTS__DEVMODE = ["localhost"]

BASE_URL = "//%(app_name)s.%(user)s.uber.space/"
BASE_URL__DEVMODE = "//localhost:%(port)s"

deployment_path = "/home/%(user)s/%(PROJECT_NAME)s-deployment/%(app_name)s"

# name (not path)
venv = "%(PROJECT_NAME)s-venv"

pip_command = "pip3.11"
python_version = "python3.11"


DEBUG = false
DEBUG__DEVMODE = true


# secret keys can be created with: python3 -c "import secrets; print(secrets.token_urlsafe(50))"
SECRET_KEY = 'NfdysN_yXKWuliPb--example--W5_Fc9VUDOVnPgUBJ2oeq6FjAOJykFWFpK1PL7URw'
